site_name: CSIRT-MU Writeups

theme:
  name: material
  locale: en
  custom_dir: overrides
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono
  favicon: https://cdn.muni.cz/media/3177659/csirtmu-favicon.ico"
  logo: assets/logo-cropped.png

  features:
    - content.tabs.link # Linked code tabs
    - content.code.copy # Code copy button
    - navigation.tracking # Anchor tracking
    - navigation.top # Back-to-top button
    - search.highlight # Highlight searched terms
    - toc.follow  # Anchor following
plugins:
  - search:
      lang: en
  - include-markdown

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Home: index.md
  - Blog:
      - "eSCL protocol": content/blog/escl.md
  - "Hack The Box Machines":
      - Agile: content/htb/Machines/Agile/writeup.md
      - Alert: content/htb/Machines/Alert/writeup.md
      - Analytics: content/htb/Machines/Analytics/writeup.md
      - Authority: content/htb/Machines/Authority/writeup.md
      - Backdoor: content/htb/Machines/Backdoor/writeup.md
      - Bizness: content/htb/Machines/Bizness/writeup.md
      - Broker: content/htb/Machines/Broker/writeup.md
      - Broscience: content/htb/Machines/Broscience/writeup.md
      - Busqueda: content/htb/Machines/Busqueda/writeup.md
      - Chemistry: content/htb/Machines/Chemistry/writeup.md
      - Clicker: content/htb/Machines/Clicker/writeup.md
      - Codify: content/htb/Machines/Codify/writeup.md
      - Crafty: content/htb/Machines/Crafty/writeup.md
      - Cypher: content/htb/Machines/Cypher/writeup.md
      - Devvortex: content/htb/Machines/Devvortex/writeup.md
      - Editorial: content/htb/Machines/Editorial/writeup.md
      - Escape: content/htb/Machines/Escape/writeup.md
      - Headless: content/htb/Machines/Headless/writeup.md
      - Heal: content/htb/Machines/Heal/writeup.md
      - Hospital: content/htb/Machines/Hospital/writeup.md
      - IClean: content/htb/Machines/IClean/writeup.md
      - Keeper: content/htb/Machines/Keeper/writeup.md
      - LinkVortex: content/htb/Machines/LinkVortex/writeup.md
      - Manager: content/htb/Machines/Manager/writeup.md
      - MetaTwo: content/htb/Machines/MetaTwo/writeup.md
      - MonitorsThree: content/htb/Machines/MonitorsThree/writeup.md
      - MonitorsTwo: content/htb/Machines/MonitorsTwo/writeup.md
      - Nocturnal: content/htb/Machines/Nocturnal/writeup.md
      - PC: content/htb/Machines/PC/writeup.md
      - Perfection: content/htb/Machines/Perfection/writeup.md
      - Photobomb: content/htb/Machines/Photobomb/writeup.md
      - Pilgrimage: content/htb/Machines/Pilgrimage/writeup.md
      - Planning: content/htb/Machines/Planning/writeup.md
      - Pov: content/htb/Machines/Pov/writeup.md
      - Precious: content/htb/Machines/Precious/writeup.md
      - Previse: content/htb/Machines/Previse/writeup.md
      - Sau: content/htb/Machines/Sau/writeup.md
      - Shoppy: content/htb/Machines/Shoppy/writeup.md
      - Soccer: content/htb/Machines/Soccer/writeup.md
      - Surveillance: content/htb/Machines/Surveillance/writeup.md
      - Titanic: content/htb/Machines/Titanic/writeup.md
      - Topology: content/htb/Machines/Topology/writeup.md
      - TwoMilion: content/htb/Machines/TwoMilion/writeup.md
      - TwoMillion: content/htb/Machines/TwoMillion/writeup.md
      - Visual: content/htb/Machines/Visual/writeup.md
      - Wifinetic: content/htb/Machines/Wifinetic/writeup.md
      - WifineticTwo: content/htb/Machines/WifineticTwo/writeup.md
      - Zipping: content/htb/Machines/Zipping/writeup.md
  - "Hack The Box Challenges":
      - Crypto-babyencryption: content/htb/Challenges/crypto-babyencryption.md
      - Crypto-baby-time-capsule: content/htb/Challenges/crypto-baby-time-capsule.md
      - Crypto-rlotto: content/htb/Challenges/crypto-rlotto.md
      - Crypto-rsaiseasy: content/htb/Challenges/crypto-rsaiseasy.md
      - Crypto-the-last-dance: content/htb/Challenges/crypto-the-last-dance.md
      - Crypto-xorxorxor: content/htb/Challenges/crypto-xorxorxor.md
      - Forensics-diagnostic: content/htb/Challenges/forensics-diagnostic.md
      - Misc-canvas: content/htb/Challenges/misc-canvas.md
      - Misc-deterministic: content/htb/Challenges/misc-deterministic.md
      - Misc-man-in-the-middle: content/htb/Challenges/misc-man-in-the-middle.md
      - Web-apacheblaze: content/htb/Challenges/web-apacheblaze.md
      - Web-cop: content/htb/Challenges/web-cop.md
      - Web-insomnia: content/htb/Challenges/web-insomnia.md
      - Web-jscalc: content/htb/Challenges/web-jscalc.md
      - Web-lovetok: content/htb/Challenges/web-lovetok.md
      - Web-neonify: content/htb/Challenges/web-neonify.md
      - Web-petpet-rcbee: content/htb/Challenges/web-petpet-rcbee.md
      - Web-phonebook: content/htb/Challenges/web-phonebook.md
      - Web-proxyasaservice: content/htb/Challenges/web-proxyasaservice.md
      - Web-renderquest: content/htb/Challenges/web-renderquest.md
      - Web-saturn: content/htb/Challenges/web-saturn.md
      - Web-templated: content/htb/Challenges/web-templated.md
      - Web-toxic: content/htb/Challenges/web-toxic.md


extra: # Remove "Made with MkDocs" footer
  generator: false

extra_css:
  - stylesheets/extra.css


copyright: "© <script> document.write(new Date().getFullYear()); </script> CSIRT-MU"
